server:
  port: 8080

spring:
  application:
    name: msvc-course

  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/coursedb
    username: postgres
    password: "1234"

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

eureka:
  instance:
    hostname: localhost

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    com.microservice: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    com.netflix.eureka: DEBUG
    org.springframework.cloud.config: DEBUG